uint8 READ=1
uint8 WRITE=0
uint8 GM_FRONT=1
uint8 GM_RIGTH=2
uint8 GM_BACK=3
uint8 GM_LEFT=4

uint8 motor_id									# GM_FRONT, GM_RIGTH, GM_BACK or GM_RIGHT
morus_uav_ros_msgs/GmParameters gm_params_sv
uint8 acu_id_sv									# GM_FRONT, GM_RIGTH, GM_BACK or GM_RIGHT
uint8 get_set_flag								# READ or WRITE value
---
bool ok